# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  container.repository: phenixita/ic6weather
  docker.buildContext: src

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    
    - task: Docker@2
      displayName: Build and push
      inputs:
        containerRegistry: 'DockerHubPhenixita'
        repository: $(container.repository)
        command: 'buildAndPush'
        Dockerfile: 'src/IC6.Weather/Dockerfile'
        buildContext: $(docker.buildContext)
        tags: |
          $(tag)
          latest

- stage: 'AKS'
  displayName: 'Deploy to AKS'
  jobs:
    - job: Deploy
      displayName: Deploy yml
      pool:
        vmImage: ubuntu-latest
      steps:
        
        - task: KubernetesManifest@0
          inputs:
            action: 'deploy'
            kubernetesServiceConnection: 'K8sDesktop-ic6-aks-default-1575237123661'
            namespace: 'default'
            manifests: '.k8s/weatherservice.service.yml'