# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  container.repository: phenixita/ic6weather
  docker.buildContext: src

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    
    - task: Docker@2
      displayName: Build and push weather server
      inputs:
        containerRegistry: 'DockerHubPhenixita'
        repository: $(container.repository)server
        command: 'buildAndPush'
        Dockerfile: 'src/IC6.Weather/Dockerfile'
        buildContext: $(docker.buildContext)
        tags: |
          $(tag)
          latest

    - task: Docker@2
      displayName: Build and push weather client
      inputs:
        containerRegistry: 'DockerHubPhenixita'
        repository: $(container.repository)client
        command: 'buildAndPush'
        Dockerfile: 'src/IC6.WeatherClient/Dockerfile'
        buildContext: $(docker.buildContext)
        tags: |
          $(tag)
          latest

    - task: Docker@2
      displayName: Build and push weather data layer
      inputs:
        containerRegistry: 'DockerHubPhenixita'
        repository: $(container.repository)datalayer
        command: 'buildAndPush'
        Dockerfile: 'src/IC6.Weather.DataLayer/Dockerfile'
        buildContext: $(docker.buildContext)
        tags: |
          $(tag)
          latest

- stage: 'AKS'
  displayName: 'Deploy to AKS'
  jobs:
    - job: Deploy
      displayName: Deploy yml
      pool:
        name: default
      steps:
        - task: Kubernetes@1
          enabled: false
          inputs:
            connectionType: 'None'
            command: 'apply'
            useConfigurationFile: true
            configuration: 'src/.k8s/'
            secretType: 'dockerRegistry'
            containerRegistryType: 'Azure Container Registry'