{
 "title": "Weather",
 "tags": [
  "weather",
  "k8s"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Weather Client Avg response time (s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_sum{job=\"weatherclient\",controller=\"Home\",action=\"Index\"}) / sum(http_requests_received_total{job=\"weatherclient\",controller=\"Home\",action=\"Index\"})"
    },
    {
     "expr": "sum(http_request_duration_seconds_sum{controller=\"WeatherForecast\"}) / sum(http_requests_received_total{controller=\"WeatherForecast\"})"
    }
   ]
  },
  {
   "title": ".NET Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "dotnet_total_memory_bytes" },
    {}
   ]
  },
  {
   "title": "HTTP Requests in progress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "http_requests_in_progress" }
   ]
  }
 ]
}