apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherdatalayer
spec:
  selector:
    matchLabels:
      app: weatherdatalayer
  template:
    metadata:
      labels:
        app: weatherdatalayer
    spec:
      containers:
      - name: weatherdatalayer
        image: phenixita/ic6weatherdatalayer:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80